---

# Change to make non-empty commit and trigger push event
# rel: 0

stages:
  - .guard
  - lint
  - test
  - bump-version
  - build

variables:
  # Set 0 to disable linting jobs
  LINTING_ENABLED: true
  TESTING_ENABLED: true

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'
  - project: 'saltbox/ci-lib'
    file: 'set-version.yml'


.python-base:
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
  image: python:3.12-alpine
  before_script:
    - mkdir --parents "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" git
    - pip3 install -e .[dev]
  cache:
    paths:
      - '$PIP_CACHE_DIR'
      - '$APK_CACHE_DIR'


.lint-job:
  stage: lint
  extends: .python-base
  rules:
    - if: $LINTING_ENABLED == 'true'


Ruff:
  extends: .lint-job
  script: ruff check saltbox_core


Mypy:
  extends: .lint-job
  script: mypy saltbox_core


Pytest:
  stage: test
  extends: .python-base
  variables:
    SALTBOX_ENV_FILE: 'tests/test.env'
  script:
    - pytest
  coverage: '/^TOTAL.+?(\d+\%)$/'
  rules:
    - if: $TESTING_ENABLED == 'true'


Bump Core version:
  stage: bump-version
  extends: .set-backend-version
  variables:
    INNER_VERSION_FILE: 'saltbox_core/__init__.py'


Build Core image:
  stage: build
  extends: .build-image
  variables:
    TARGET: main


Trigger API Client pipeline:
  stage: build
  variables:
    MODULE_NAME: saltbox_core
    SALTBOX_ENV_FILE: 'tests/test.env'
  trigger:
    include:
      - project: 'saltbox/ci-lib'
        file: 'gen-api-client.yml'
    strategy: mirror
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'


# vim: filetype=yaml.gitlab
