stages:
  - build-scheme
  - build-api-client
  - deploy

OpenAPI scheme:
  stage: build-scheme
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
    SALTBOX_ENV_FILE: 'tests/test.env'
  image: python:3.12-alpine
  before_script:
    - mkdir --parents "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" git
    - pip3 install -e .[dev]
  script:
    - VERSION=$(python3 -c 'import saltbox_core; print(saltbox_core.__version__)')
    - echo "PYTHON_VERSION=$VERSION" > build.env
    - python ./saltbox_core/utilities/generate_openapi.py
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - openapi.json
    expire_in: 1 day
  cache:
    paths:
      - '$PIP_CACHE_DIR'
      - '$APK_CACHE_DIR'


.api-client-generate:
  image:  openapitools/openapi-generator-cli:v7.14.0
  stage: build-api-client
  dependencies:
    - 'OpenAPI scheme'
  artifacts:
    untracked: true
    expire_in: 1 day
  script:
    - bash /usr/local/bin/docker-entrypoint.sh generate
      --config ./openapi-generator-config.json
      --additional-properties=npmName=@saltbox/${CI_PROJECT_NAME}-api-client
      --additional-properties=npmVersion=${VERSION}


Build API Client:
  extends: .api-client-generate
  variables:
    VERSION: "${PYTHON_VERSION}"
  rules:
    - if: $CI_COMMIT_TAG =~ $VERSION_TAG_PATTERN


Build API Client Nightly:
  extends: .api-client-generate
  variables:
    VERSION: "${PYTHON_VERSION}-${CI_COMMIT_SHA}"
  rules:
    - if: $CI_COMMIT_TAG !~ $VERSION_TAG_PATTERN


Upload API Client:
  image:  node:22.18.0
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm install
    - npm config set @saltbox:registry https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm publish
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
