services:
  salt_master:
    build:
      context: salt/
      target: salt-master
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SALT_VERSION: ${SALT_VERSION}
        PYTHON_VERSION: ${SALT_PYTHON_VERSION}
    container_name: fastms-salt-master
    environment:
      - SALT_MASTER=true
      - SALT_SHARED_SECRET=mysecretpassword
    ports:
      - '4505-4506:4505-4506'
      - '8001:8000'
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: fastms-redis
    ports:
      - '6379:6379'
  backend:
    build:
      context: backend/
      target: builder
      args:
        PYTHON_VERSION: '3.12'
    develop:
      watch:
        - action: rebuild
          path: backend/
    container_name: fastms-application
    env_file:
      - .env
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - redis
  salt_minion:
    build:
      context: salt/
      target: salt-minion
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SALT_VERSION: ${SALT_VERSION}
        PYTHON_VERSION: ${SALT_PYTHON_VERSION}
    # container_name: fastms-salt-minion
    environment:
      - SALT_MINION=true
    deploy:
      mode: replicated
      replicas: ${MINION_REPLICAS:-1}
