services:
  salt_master:
    build:
      context: salt/
      target: salt-master
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SALT_VERSION: ${SALT_VERSION}
        PYTHON_VERSION: ${SALT_PYTHON_VERSION}
    init: true
    develop:
      watch:
        - action: rebuild
          path: salt/
    container_name: fastms-salt-master
    environment:
      - SALT_MASTER=true
    ports:
      - '4505-4506:4505-4506'
    volumes:
      - 'salt_master_pki:/etc/salt/pki/'
    depends_on:
      - redis
  redis:
    image: redis:7.2-alpine
    container_name: fastms-redis
    ports:
      - '6379:6379'
  backend:
    build:
      context: backend/
      target: builder
      args:
        PYTHON_VERSION: '3.12'
    develop:
      watch:
        - action: rebuild
          path: backend/
    container_name: fastms-application
    env_file:
      - .env
    environment:
      SALT_URL: 'https://fastms-salt-master:8000'
      REDIS_URL: 'redis://fastms-redis:6379/0'
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - redis
  salt_minion:
    build:
      context: salt/
      target: salt-minion
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        SALT_VERSION: ${SALT_VERSION}
        PYTHON_VERSION: ${SALT_PYTHON_VERSION}
    init: true
    develop:
      watch:
        - action: rebuild
          path: salt/
    # container_name: fastms-salt-minion
    environment:
      - SALT_MINION=true
    deploy:
      mode: replicated
      replicas: ${MINION_REPLICAS:-1}
volumes:
  salt_master_pki: {}
