[project]
dynamic = [ 'dependencies', 'version' ]
name = 'fastms-core'
requires-python = '>=3.10'
license = { 'text' = 'N/A' }  # FIXME
description = ''
readme = 'README.md'
classifiers = [
  'Topic :: System :: Systems Administration',
]

[project.optional-dependencies]
dev = [
    'Flake8-pyproject',
    'flake8',
    'flake8-logging',
    'ipython',
    'mypy>=1.15.0',
    'pre-commit',
    'pylint',
    'types-redis',
    'python-lsp-server[all]',
    'types-PyYAML',
    'types-requests',
    'ruff',
    'taskiq[reload]',
    "coverage[toml]>=7.6.11",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest-sugar>=1.0.0",
    "mongomock>=4.3.0",
]

[project.scripts]
salt-box-faststream-redis = 'salt_box_core.event_bus.faststream_redis:main'
salt-box-tasks-watcher = 'salt_box_core.tasks.tasks_watcher:main'

[metadata]
url = 'https://gitlab.com/fastms'
version = 'attr: package.__version__'

[build-system]
requires = ['setuptools>=57.4.0', 'setuptools-scm']
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages.find]
# Explicit package dir for flat-layout
include = ['salt_box_core', 'salt_box_core.*']

[tool.setuptools.dynamic]
dependencies = { file = ['requirements.txt'] }
version = { attr = 'salt_box_core.__version__' }

[tool.flake8]
max-line-length = 120
extend-ignore = [ ]

[tool.mypy]
check_untyped_defs = true
plugins = [ 'pydantic.mypy' ]
python_version = '3.12'
ignore_missing_imports = false
color_output = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ['venv/', '.venv/', 'autotests/*', 'tests/*']
strict = true
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
implicit_reexport = false
show_error_codes = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = 'function'
minversion = "8.0"
addopts = [
    "--cov=salt_box_core",
    "--cov-report=term-missing",
    "--durations=5",
    # "--maxfail=1",
    # "--disable-warnings -q",
]
testpaths = ["tests"]
# env_files = [".env.example"]

[tool.coverage.run]
# concurrency = ["gevent"]
# branch = true
source = ["salt_box_core"]
omit = ["main.py", "config.py", "tests/*", "venv/*", ".venv/*", "autotests/*", "**/__init__.py"]

[tool.coverage.report]
show_missing = true
# fail_under = 60
exclude_lines = [
  'if TYPE_CHECKING:',
  'pragma: no cover',
  "if __name__ == '__main__':",
]
# skip_covered = true
