[project]
name = 'fastms-core'
version = '0.0.0'
requires-python = '>=3.9'
license = { 'text' = 'N/A' }  # FIXME
description = ''
readme = 'README.md'
dependencies = [ ]

[project.optional-dependencies]
dev = [
  'flake8',
  'ipython',
  'mypy',
  'pre-commit',
  'pylint',
  'types-redis',
]

[project.scripts]

[metadata]
url = 'https://gitlab/fastms'

[build-system]
requires = ['setuptools', 'setuptools-scm']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
package-dir = { 'fastms_core.backend' = 'backend/' }

[tool.mypy]
check_untyped_defs = true
