[project]
dynamic = [ 'dependencies', 'version' ]
name = 'fastms-core'
requires-python = '>=3.10'
license = { 'text' = 'N/A' }  # FIXME
description = ''
readme = 'README.md'
classifiers = [
  'Topic :: System :: Systems Administration',
]

[project.optional-dependencies]
dev = [
    'Flake8-pyproject',
    'flake8',
    'flake8-logging',
    'ipython',
    'mypy',
    'pre-commit',
    'pylint',
    'types-redis',
    'python-lsp-server[all]',
    'types-PyYAML',
    'types-requests',
    'ruff',
]

[project.scripts]
salt-box-minions-consumer = 'fastms_core.minions.consumer:main'
salt-box-tasks-watcher = 'fastms_core.tasks.tasks_watcher:main'

[metadata]
url = 'https://gitlab.com/fastms'
version = 'attr: package.__version__'

[build-system]
requires = ['setuptools>=57.4.0', 'setuptools-scm']
build-backend = 'setuptools.build_meta'

[tool.setuptools.packages.find]
# Explicit package dir for flat-layout
include = ['fastms_core', 'fastms_core.*']

[tool.setuptools.dynamic]
dependencies = { file = ['requirements.txt'] }
version = { attr = 'fastms_core.__version__' }

[tool.flake8]
max-line-length = 120
extend-ignore = [ ]

[tool.mypy]
check_untyped_defs = true
plugins = [ 'pydantic.mypy' ]
python_version = '3.12'
ignore_missing_imports = false
color_output = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ['venv/', '.venv/', 'autotests/*', 'tests/*']
strict = true
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
implicit_reexport = false
show_error_codes = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true
